ARG ELASTIC_STACK_VERSION

# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:${ELASTIC_STACK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>