---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: deep-kibana
server.host: "0.0.0.0"
elasticsearch.url: http://elasticsearch:9200
elasticsearch.password: ${ELASTIC_PASSWORD}